### ISSUE TITLE
IllegalArgumentException: Component is already contained in Container

### ISSUE THREAD

**Issue by arthef** [shannah/RADChatRoom#1]
Hi,
I am going through the tutorial and I am at step 6. So, very simple code, just the beginning. The app compiles but I am getting the error at runtime:
```
java.lang.IllegalArgumentException: Component is already contained in Container: Container[x=0 y=0 width=0 height=0 name=null, layout = BoxLayout, scrollableX = false, scrollableY = false, components = [TextAreaPropertyView]]
	at com.codename1.ui.Container.insertComponentAtImpl(Container.java:927)
	at com.codename1.ui.Container.insertComponentAt(Container.java:918)
	at com.codename1.ui.Container.addComponent(Container.java:840)
	at com.codename1.ui.Container.encloseIn(Container.java:250)
	at com.codename1.ui.layouts.BoxLayout.encloseYCenter(BoxLayout.java:447)
	at com.codename1.rad.ui.chatroom.ChatRoomView.<init>(ChatRoomView.java:281)
	at com.codename1.rad.ui.chatroom.ChatRoomView.<init>(ChatRoomView.java:112)
	at com.example.controller.ChatFormController.<init>(ChatFormController.kt:16)
```
Do you have any suggestions on what can be wrong? My code is the exact copy of the code from examples in the tutorial.

**Comment by shannah** [comment]
Can you post your code here too?

**Comment by arthef** [comment]
Sure, here it is. It is in Kotlin:
Main class:
``` kotlin
package com.example

import com.codename1.rad.controllers.ApplicationController
import com.codename1.rad.controllers.ControllerEvent
import com.example.controller.ChatFormController

open class ExampleApp: ApplicationController() {

    override fun actionPerformed(evt: ControllerEvent?) {
        if (evt is StartEvent) {
            evt.consume()
            ChatFormController(this).view.show()
        }
    }

}
```
The controller class:
``` kotlin
package com.example.controller

import com.codename1.rad.controllers.Controller
import com.codename1.rad.controllers.FormController
import com.codename1.rad.models.Entity
import com.codename1.rad.ui.chatroom.ChatBubbleView
import com.codename1.rad.ui.chatroom.ChatRoomView
import com.codename1.ui.CN.CENTER
import com.codename1.ui.Form
import com.codename1.ui.layouts.BorderLayout


class ChatFormController(parent: Controller) : FormController(parent) {
    init {
        val f = Form("My First Chat Room", BorderLayout())
        val view = ChatRoomView(createViewModel(), f)
        f.add(CENTER, view)
        setView(f)
    }

    private fun createViewModel(): Entity {
        val room = ChatRoomView.ViewModel()

        val message = ChatBubbleView.ViewModel()
        message.messageText("Hello World")
        room.addMessages(message)
        return room
    }
}
```

**Comment by shannah** [comment]
Thanks.   I've fixed this bug in git and rebuilt.  You'll need to update the RADChatRoom cn1lib from [here](https://github.com/shannah/RADChatRoom/tree/master/bin)

Updates will be in Codename One settings versions within a few days.

While your at it, update the CodeRAD.cn1lib from there also.

**Comment by arthef** [comment]
Thank you for fast response. However, I am still stuck with the same error. Here what I did:
* Cloned your RAD Chat github repository
* copied files from RADChatRoom/bin/* to my project lib/
* diff RADChatRoom/bin/RADChatRoom.cn1lib myproject/lib/RADChatRoom.cn1lib shows no difference
* Rebuilt my project
* Started in simulator with the same error. Stack points to the same code lines in the same files

**Comment by arthef** [comment]
I did some more digging and it seems that you, by mistake, uploaded old files instead of new. The files in the bin directory are identical to files in uploaded by codenameone refresh libs.
Could you please re-upload new files?

**Comment by shannah** [comment]
They are the correct files.
Copy those files into your project's lib directory.  Then select "Refresh cn1libs"

![image](https://user-images.githubusercontent.com/2677562/79388591-706c9000-7f22-11ea-863d-9b1dd9af7012.png)

**Comment by arthef** [comment]
Thank you.

**Comment by shannah** [comment]
@arturhefczyc No.  Thank you.  You might be the first person going through this tutorial.  While this tutorial is finished, and the RADChatRoom component is finished, it is just one piece of a larger project that I'm working on that hasn't yet been released.  Your feedback is valuable and appreciated.
