### ISSUE TITLE
Chat input field does not regain focus after message is sent

### ISSUE THREAD

**Issue by arthef** [shannah/RADChatRoom#14]
Hi,
When on desktop and message is sent with ENTER it all works as expected. However, on mobile when a message is sent using "SEND" button, the input field does not regains focus after message is sent.
This leads to bad user experience as a user has to press "send" and then, again press on the input line to continue typing a message.

Correct behavior seems to make the focus return to the input field after message is sent.

**Comment by shannah** [comment]
Updated build [here](https://github.com/shannah/RADChatRoom/tree/master/bin)

Will be in CodenameOne settings soon.

**Comment by arthef** [comment]
Works as expected now, thank you for the fix.
