### ISSUE TITLE
RFE: option to disable swipe

### ISSUE THREAD

**Issue by jsfan3** [shannah/RADChatRoom#18]
Currently the swipe on the right to see time details can be nice, but in some circumstances it's better disabled. For example, I have to develop an app in which the swipe will be used to change the Form: in this case, the swipe of the RADChatRoom and the swipe that I'll add to change the Form will conflict.

**Comment by shannah** [comment]
I've added this feature.  Documented [here](https://shannah.github.io/RADChatRoom/cookbook/#_disabling_swipe_left_to_reveal_time_posted)

You'll need to update both CodeRAD and RADChatRoom [here](https://github.com/shannah/RADChatRoom/tree/master/bin).  Will be updated in Codename one settings soon.
