### ISSUE TITLE
Scroll to the last chat message

### ISSUE THREAD

**Issue by arthef** [shannah/RADChatRoom#19]
Hi,
When a new chat room view is opened it is usually populated with a list of existing/old messages loaded from the server. A preferred behavior might be to scroll the view to the last message or better yet to the first unread message on the list.
What would be the best way to scroll the chat room view to the last message or a specific message after the view is created?

**Comment by shannah** [comment]
I've added a scrollToMessage() method to ChatRoomView.  You can download the latest [here](https://github.com/shannah/RADChatRoom/tree/master/bin).  It will be in CodenameOne settings soon. 

See a sample usage [here](https://github.com/codenameone/CodenameOne/blob/06bb25b4f969c107e523d1f14b67e6cb5e140211/Samples/samples/RADChatRoomTest3/RADChatRoomTest3.java#L125-L127)

**Comment by arthef** [comment]
Works as expected, thank you.
