### ISSUE TITLE
CSS customization

### ISSUE THREAD

**Issue by arthef** [shannah/RADChatRoom#2]
Hi,
Is there any way to customize the look of the app, bubble colors and other elements through CSS?

**Comment by shannah** [comment]
Yes.  Haven't done documentation on this yet, but you can easily see the UIIDs that you can style by either using the Component Inspector in the simulator, or just look at the source of [ChatBubbleView](https://github.com/shannah/RADChatRoom/blob/master/src/com/codename1/rad/ui/chatroom/ChatBubbleView.java), and do a find for "setUIID", which indicates setting a UIID, which can be accessed as CSS selectors.

The relevant ones for the chat bubbles:

- `ChatBubbleSpanLabelOwn` - The UIID for chat bubbles that you post yourself.
- `ChatBubbleTextOwn` - The UIID for the text in the chat bubble you post.
- `ChatBubbleTextOwnDesktop` - The UIID for text in the chat bubble you post - for desktop (on desktop the text is a little bigger)
- `ChatBubbleSpanLabelOther` - The UIID for chat bubbles that others post
- `ChatBubbleTextOther` - The UIID for the text in the chat bubble others post.
- `ChatBubbleTextOtherDesktop` - The UIID for text in the chat bubble others post - for desktop (on desktop the text is a little bigger)

**Comment by arthef** [comment]
Thanks again!
