### ISSUE TITLE
Invalid Maven dependencies

### ISSUE THREAD

**Issue by joostcore** [shannah/RADChatRoom#20]
Hello :)

On initializing the project various dependencies and plugins could not be resolved by maven.
Has someone fixed this ?

`
Cannot resolve com.codenameone:codenameone-core:7.0.16-SNAPSHOT
Cannot resolve com.codenameone:chat-ui-kit-lib:1.0.1-SNAPSHOT
Cannot resolve com.codenameone:codenameone-javase:7.0.16-SNAPSHOT
Cannot resolve plugin org.apache.maven.plugins:maven-source-plugin:<unknown>
Cannot resolve plugin org.apache.maven.plugins:maven-source-plugin:<unknown>
Cannot resolve plugin com.codenameone:codenameone-maven-plugin:7.0.16-SNAPSHOT
Cannot resolve plugin org.codehaus.mojo:build-helper-maven-plugin:<unknown>
Cannot resolve plugin org.apache.maven.plugins:maven-source-plugin:<unknown>
Cannot resolve plugin com.codenameone:codenameone-maven-plugin:7.0.16-SNAPSHOT
Cannot resolve plugin org.apache.maven.plugins:maven-source-plugin:<unknown>
Cannot resolve plugin com.codenameone:codenameone-maven-plugin:7.0.16-SNAPSHOT
Cannot resolve plugin org.apache.maven.plugins:maven-source-plugin:<unknown>
Cannot resolve plugin org.apache.maven.plugins:maven-source-plugin:<unknown>
Cannot resolve plugin org.apache.maven.plugins:maven-source-plugin:<unknown>
Cannot resolve plugin org.apache.maven.plugins:maven-source-plugin:<unknown>
Cannot resolve plugin org.apache.maven.plugins:maven-source-plugin:<unknown>
Cannot resolve plugin org.apache.maven.plugins:maven-source-plugin:<unknown>
Cannot resolve plugin org.apache.maven.plugins:maven-source-plugin:<unknown>

`

Best regards

Joost

**Comment by shannah** [comment]
Change the cn1.version and cn1.plugin.version properties in the pom.xml to 7.0.38
