### ISSUE TITLE
Bubble shape hardcoded - maybe it could be defined through CSS?

### ISSUE THREAD

**Issue by arthef** [shannah/RADChatRoom#5]
I wonder if it would be possible to change the implementation to have the bubble entire look defined in CSS?
I worked on a similar app in JavaFX and it was possible to define shape of the background label with round corners, all the colors, gradients, etc.... I am not sure if it is possible with Codename One, but it could be really useful.

**Comment by shannah** [comment]
I've added support for this and have written some instructions on this [here](https://shannah.github.io/RADChatRoom/cookbook/#_customizing_chat_bubbles_using_css)

Unfortunately, this depends on some modifications that I've made to the CSS compiler which won't be available yet.  Probably out next friday.
