### ISSUE TITLE
Add 'text' tag to ChatMessage schema

### ISSUE THREAD

**Issue by arthef** [shannah/RADChatRoom#8]
I am wondering why there is no message content tag added to ChatMessage schema. The schema for Message on https://schema.org/Message has 'text' property which is supposed to keep the content of the message.
Is this something missing from the ChatMessage?

**Comment by arthef** [comment]
Hm, I guess, I posted this issue to incorrect project. It should probably be added to the CodeRAD project.

**Comment by shannah** [comment]
The "text" Tag is in the CreativeWork schema, which ChatMessage inherits from.  So ChatMessage does indeed have a "text" Tag, it is it used for the text of the chat message.

**Comment by arthef** [comment]
Ah, indeed, thank you!
